apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  type: NodePort
  selector:
    app: hello-python
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
